name: Update Subjects

on:
  push:
    paths:
      - 'flashcards/*.json'
      - 'update_subjects.py'
      # Excluding changes to subjects.json to prevent infinite loops

jobs:
  update-subjects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Check if commit is from GitHub Actions
        if: github.actor == 'github-actions[bot]'
        run: |
          echo "Commit made by GitHub Actions. Exiting workflow."
          exit 0

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip

      - name: Run Update Subjects Script
        run: |
          python update_subjects.py

      - name: Check for Changes
        id: git-check
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add subjects.json
          git diff --cached --exit-code || echo "::set-output name=changed::true"

      - name: Commit and Push if Changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git commit -m "Auto-update subjects.json"
          git push
